name: healthsync
description: "Offline-first hospital management system for small clinics"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6

  # Form Helpers & Security
  email_validator: ^3.0.0
  flutter_secure_storage: ^9.2.4

  # State & Utilities
  provider: ^6.1.1
  mask_text_input_formatter: ^2.0.0
  intl: ^0.19.0
  flutter_sms: ^2.3.1
  image_picker: ^0.8.7+5
  connectivity_plus: ^4.0.0
  path: ^1.8.3
  uuid: ^4.5.1
  
  # UI Components
  syncfusion_flutter_charts: ^29.2.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/logo.png
  