// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAWCGSMA3KflsOSRiPQ8EYlUURYKivhr0',
    appId: '1:524815217655:web:fd0dc67a70ee53a44474f2',
    messagingSenderId: '524815217655',
    projectId: 'healthsync-53d08',
    authDomain: 'healthsync-53d08.firebaseapp.com',
    storageBucket: 'healthsync-53d08.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABbk9fOJG7Y0MUarIf2KkI7jsFfOkxD2c',
    appId: '1:524815217655:android:309803c694bdd5e14474f2',
    messagingSenderId: '524815217655',
    projectId: 'healthsync-53d08',
    storageBucket: 'healthsync-53d08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBryrTA1VveLxuvmCVsdIp5sodHsKTIr8I',
    appId: '1:524815217655:ios:57c9687755dee10c4474f2',
    messagingSenderId: '524815217655',
    projectId: 'healthsync-53d08',
    storageBucket: 'healthsync-53d08.firebasestorage.app',
    iosBundleId: 'com.example.healthsync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBryrTA1VveLxuvmCVsdIp5sodHsKTIr8I',
    appId: '1:524815217655:ios:57c9687755dee10c4474f2',
    messagingSenderId: '524815217655',
    projectId: 'healthsync-53d08',
    storageBucket: 'healthsync-53d08.firebasestorage.app',
    iosBundleId: 'com.example.healthsync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAWCGSMA3KflsOSRiPQ8EYlUURYKivhr0',
    appId: '1:524815217655:web:972afdcca855576e4474f2',
    messagingSenderId: '524815217655',
    projectId: 'healthsync-53d08',
    authDomain: 'healthsync-53d08.firebaseapp.com',
    storageBucket: 'healthsync-53d08.firebasestorage.app',
  );

}